/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppAvailabilityCreateRequestDataAttributes
 */
export interface AppAvailabilityCreateRequestDataAttributes {
    /**
     * 
     * @type {boolean}
     * @memberof AppAvailabilityCreateRequestDataAttributes
     */
    availableInNewTerritories: boolean;
}

/**
 * Check if a given object implements the AppAvailabilityCreateRequestDataAttributes interface.
 */
export function instanceOfAppAvailabilityCreateRequestDataAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "availableInNewTerritories" in value;

    return isInstance;
}

export function AppAvailabilityCreateRequestDataAttributesFromJSON(json: any): AppAvailabilityCreateRequestDataAttributes {
    return AppAvailabilityCreateRequestDataAttributesFromJSONTyped(json, false);
}

export function AppAvailabilityCreateRequestDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAvailabilityCreateRequestDataAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableInNewTerritories': json['availableInNewTerritories'],
    };
}

export function AppAvailabilityCreateRequestDataAttributesToJSON(value?: AppAvailabilityCreateRequestDataAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availableInNewTerritories': value.availableInNewTerritories,
    };
}

