/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityRelationshipsAppData } from './AppAvailabilityRelationshipsAppData';
import {
    AppAvailabilityRelationshipsAppDataFromJSON,
    AppAvailabilityRelationshipsAppDataFromJSONTyped,
    AppAvailabilityRelationshipsAppDataToJSON,
} from './AppAvailabilityRelationshipsAppData';

/**
 * 
 * @export
 * @interface AppAvailabilityCreateRequestDataRelationshipsApp
 */
export interface AppAvailabilityCreateRequestDataRelationshipsApp {
    /**
     * 
     * @type {AppAvailabilityRelationshipsAppData}
     * @memberof AppAvailabilityCreateRequestDataRelationshipsApp
     */
    data: AppAvailabilityRelationshipsAppData;
}

/**
 * Check if a given object implements the AppAvailabilityCreateRequestDataRelationshipsApp interface.
 */
export function instanceOfAppAvailabilityCreateRequestDataRelationshipsApp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function AppAvailabilityCreateRequestDataRelationshipsAppFromJSON(json: any): AppAvailabilityCreateRequestDataRelationshipsApp {
    return AppAvailabilityCreateRequestDataRelationshipsAppFromJSONTyped(json, false);
}

export function AppAvailabilityCreateRequestDataRelationshipsAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAvailabilityCreateRequestDataRelationshipsApp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AppAvailabilityRelationshipsAppDataFromJSON(json['data']),
    };
}

export function AppAvailabilityCreateRequestDataRelationshipsAppToJSON(value?: AppAvailabilityCreateRequestDataRelationshipsApp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AppAvailabilityRelationshipsAppDataToJSON(value.data),
    };
}

