/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories } from './AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories';
import {
    AppAvailabilityCreateRequestDataRelationshipsAvailableTerritoriesFromJSON,
    AppAvailabilityCreateRequestDataRelationshipsAvailableTerritoriesFromJSONTyped,
    AppAvailabilityCreateRequestDataRelationshipsAvailableTerritoriesToJSON,
} from './AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories';
import type { AppAvailabilityV2CreateRequestDataRelationshipsApp } from './AppAvailabilityV2CreateRequestDataRelationshipsApp';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsApp';

/**
 * 
 * @export
 * @interface AppAvailabilityCreateRequestDataRelationships
 */
export interface AppAvailabilityCreateRequestDataRelationships {
    /**
     * 
     * @type {AppAvailabilityV2CreateRequestDataRelationshipsApp}
     * @memberof AppAvailabilityCreateRequestDataRelationships
     */
    app: AppAvailabilityV2CreateRequestDataRelationshipsApp;
    /**
     * 
     * @type {AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories}
     * @memberof AppAvailabilityCreateRequestDataRelationships
     */
    availableTerritories: AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories;
}

/**
 * Check if a given object implements the AppAvailabilityCreateRequestDataRelationships interface.
 */
export function instanceOfAppAvailabilityCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "app" in value;
    isInstance = isInstance && "availableTerritories" in value;

    return isInstance;
}

export function AppAvailabilityCreateRequestDataRelationshipsFromJSON(json: any): AppAvailabilityCreateRequestDataRelationships {
    return AppAvailabilityCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function AppAvailabilityCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAvailabilityCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSON(json['app']),
        'availableTerritories': AppAvailabilityCreateRequestDataRelationshipsAvailableTerritoriesFromJSON(json['availableTerritories']),
    };
}

export function AppAvailabilityCreateRequestDataRelationshipsToJSON(value?: AppAvailabilityCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AppAvailabilityV2CreateRequestDataRelationshipsAppToJSON(value.app),
        'availableTerritories': AppAvailabilityCreateRequestDataRelationshipsAvailableTerritoriesToJSON(value.availableTerritories),
    };
}

