/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2CreateRequestDataRelationshipsApp } from './AppAvailabilityV2CreateRequestDataRelationshipsApp';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsApp';
import type { AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities } from './AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities';

/**
 * 
 * @export
 * @interface AppAvailabilityV2CreateRequestDataRelationships
 */
export interface AppAvailabilityV2CreateRequestDataRelationships {
    /**
     * 
     * @type {AppAvailabilityV2CreateRequestDataRelationshipsApp}
     * @memberof AppAvailabilityV2CreateRequestDataRelationships
     */
    app: AppAvailabilityV2CreateRequestDataRelationshipsApp;
    /**
     * 
     * @type {AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities}
     * @memberof AppAvailabilityV2CreateRequestDataRelationships
     */
    territoryAvailabilities: AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities;
}

/**
 * Check if a given object implements the AppAvailabilityV2CreateRequestDataRelationships interface.
 */
export function instanceOfAppAvailabilityV2CreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "app" in value;
    isInstance = isInstance && "territoryAvailabilities" in value;

    return isInstance;
}

export function AppAvailabilityV2CreateRequestDataRelationshipsFromJSON(json: any): AppAvailabilityV2CreateRequestDataRelationships {
    return AppAvailabilityV2CreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function AppAvailabilityV2CreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAvailabilityV2CreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSON(json['app']),
        'territoryAvailabilities': AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesFromJSON(json['territoryAvailabilities']),
    };
}

export function AppAvailabilityV2CreateRequestDataRelationshipsToJSON(value?: AppAvailabilityV2CreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AppAvailabilityV2CreateRequestDataRelationshipsAppToJSON(value.app),
        'territoryAvailabilities': AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesToJSON(value.territoryAvailabilities),
    };
}

