/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2CreateRequestDataRelationshipsAppData } from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';

/**
 * 
 * @export
 * @interface AppAvailabilityV2CreateRequestDataRelationshipsApp
 */
export interface AppAvailabilityV2CreateRequestDataRelationshipsApp {
    /**
     * 
     * @type {AppAvailabilityV2CreateRequestDataRelationshipsAppData}
     * @memberof AppAvailabilityV2CreateRequestDataRelationshipsApp
     */
    data: AppAvailabilityV2CreateRequestDataRelationshipsAppData;
}

/**
 * Check if a given object implements the AppAvailabilityV2CreateRequestDataRelationshipsApp interface.
 */
export function instanceOfAppAvailabilityV2CreateRequestDataRelationshipsApp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSON(json: any): AppAvailabilityV2CreateRequestDataRelationshipsApp {
    return AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSONTyped(json, false);
}

export function AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAvailabilityV2CreateRequestDataRelationshipsApp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON(json['data']),
    };
}

export function AppAvailabilityV2CreateRequestDataRelationshipsAppToJSON(value?: AppAvailabilityV2CreateRequestDataRelationshipsApp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON(value.data),
    };
}

