/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks
 */
export interface AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks {
    /**
     * 
     * @type {string}
     * @memberof AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks
     */
    self?: string;
    /**
     * 
     * @type {string}
     * @memberof AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks
     */
    related?: string;
}

/**
 * Check if a given object implements the AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks interface.
 */
export function instanceOfAppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json: any): AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks {
    return AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped(json, false);
}

export function AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : json['self'],
        'related': !exists(json, 'related') ? undefined : json['related'],
    };
}

export function AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
        'related': value.related,
    };
}

