/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppAvailabilityRelationshipsAppLinks
 */
export interface AppAvailabilityRelationshipsAppLinks {
    /**
     * 
     * @type {string}
     * @memberof AppAvailabilityRelationshipsAppLinks
     */
    self?: string;
    /**
     * 
     * @type {string}
     * @memberof AppAvailabilityRelationshipsAppLinks
     */
    related?: string;
}

/**
 * Check if a given object implements the AppAvailabilityRelationshipsAppLinks interface.
 */
export function instanceOfAppAvailabilityRelationshipsAppLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppAvailabilityRelationshipsAppLinksFromJSON(json: any): AppAvailabilityRelationshipsAppLinks {
    return AppAvailabilityRelationshipsAppLinksFromJSONTyped(json, false);
}

export function AppAvailabilityRelationshipsAppLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAvailabilityRelationshipsAppLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : json['self'],
        'related': !exists(json, 'related') ? undefined : json['related'],
    };
}

export function AppAvailabilityRelationshipsAppLinksToJSON(value?: AppAvailabilityRelationshipsAppLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
        'related': value.related,
    };
}

