/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInner } from './AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInner';
import {
    AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInnerFromJSON,
    AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInnerFromJSONTyped,
    AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInnerToJSON,
} from './AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInner';

/**
 * 
 * @export
 * @interface AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization
 */
export interface AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInner}
     * @memberof AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization
     */
    data?: AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInner;
}

/**
 * Check if a given object implements the AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization interface.
 */
export function instanceOfAppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalizationFromJSON(json: any): AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization {
    return AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalizationFromJSONTyped(json, false);
}

export function AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInnerFromJSON(json['data']),
    };
}

export function AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalizationToJSON(value?: AppClipHeaderImageRelationshipsAppClipDefaultExperienceLocalization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizationsDataInnerToJSON(value.data),
    };
}

