/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppCustomProductPageVersionRelationshipsAppCustomProductPageData } from './AppCustomProductPageVersionRelationshipsAppCustomProductPageData';
import {
    AppCustomProductPageVersionRelationshipsAppCustomProductPageDataFromJSON,
    AppCustomProductPageVersionRelationshipsAppCustomProductPageDataFromJSONTyped,
    AppCustomProductPageVersionRelationshipsAppCustomProductPageDataToJSON,
} from './AppCustomProductPageVersionRelationshipsAppCustomProductPageData';

/**
 * 
 * @export
 * @interface AppCustomProductPageVersionRelationshipsAppCustomProductPage
 */
export interface AppCustomProductPageVersionRelationshipsAppCustomProductPage {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppCustomProductPageVersionRelationshipsAppCustomProductPage
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppCustomProductPageVersionRelationshipsAppCustomProductPageData}
     * @memberof AppCustomProductPageVersionRelationshipsAppCustomProductPage
     */
    data?: AppCustomProductPageVersionRelationshipsAppCustomProductPageData;
}

/**
 * Check if a given object implements the AppCustomProductPageVersionRelationshipsAppCustomProductPage interface.
 */
export function instanceOfAppCustomProductPageVersionRelationshipsAppCustomProductPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppCustomProductPageVersionRelationshipsAppCustomProductPageFromJSON(json: any): AppCustomProductPageVersionRelationshipsAppCustomProductPage {
    return AppCustomProductPageVersionRelationshipsAppCustomProductPageFromJSONTyped(json, false);
}

export function AppCustomProductPageVersionRelationshipsAppCustomProductPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppCustomProductPageVersionRelationshipsAppCustomProductPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppCustomProductPageVersionRelationshipsAppCustomProductPageDataFromJSON(json['data']),
    };
}

export function AppCustomProductPageVersionRelationshipsAppCustomProductPageToJSON(value?: AppCustomProductPageVersionRelationshipsAppCustomProductPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppCustomProductPageVersionRelationshipsAppCustomProductPageDataToJSON(value.data),
    };
}

