/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailData } from './AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailData';
import {
    AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailDataFromJSON,
    AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailDataFromJSONTyped,
    AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailDataToJSON,
} from './AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailData';

/**
 * 
 * @export
 * @interface AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail
 */
export interface AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailData}
     * @memberof AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail
     */
    data?: AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailData;
}

/**
 * Check if a given object implements the AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail interface.
 */
export function instanceOfAppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailFromJSON(json: any): AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail {
    return AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailFromJSONTyped(json, false);
}

export function AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailDataFromJSON(json['data']),
    };
}

export function AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailToJSON(value?: AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetailDataToJSON(value.data),
    };
}

