/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInner } from './AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInner';
import {
    AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInnerFromJSON,
    AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInnerFromJSONTyped,
    AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInnerToJSON,
} from './AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInner';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface AppCustomProductPageLocalizationRelationshipsAppPreviewSets
 */
export interface AppCustomProductPageLocalizationRelationshipsAppPreviewSets {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppCustomProductPageLocalizationRelationshipsAppPreviewSets
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof AppCustomProductPageLocalizationRelationshipsAppPreviewSets
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInner>}
     * @memberof AppCustomProductPageLocalizationRelationshipsAppPreviewSets
     */
    data?: Array<AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInner>;
}

/**
 * Check if a given object implements the AppCustomProductPageLocalizationRelationshipsAppPreviewSets interface.
 */
export function instanceOfAppCustomProductPageLocalizationRelationshipsAppPreviewSets(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppCustomProductPageLocalizationRelationshipsAppPreviewSetsFromJSON(json: any): AppCustomProductPageLocalizationRelationshipsAppPreviewSets {
    return AppCustomProductPageLocalizationRelationshipsAppPreviewSetsFromJSONTyped(json, false);
}

export function AppCustomProductPageLocalizationRelationshipsAppPreviewSetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppCustomProductPageLocalizationRelationshipsAppPreviewSets {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInnerFromJSON)),
    };
}

export function AppCustomProductPageLocalizationRelationshipsAppPreviewSetsToJSON(value?: AppCustomProductPageLocalizationRelationshipsAppPreviewSets | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AppCustomProductPageLocalizationRelationshipsAppPreviewSetsDataInnerToJSON)),
    };
}

