/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData } from './AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData';
import {
    AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentDataFromJSON,
    AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentDataFromJSONTyped,
    AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentDataToJSON,
} from './AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData';

/**
 * 
 * @export
 * @interface AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument
 */
export interface AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData}
     * @memberof AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument
     */
    data?: AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData;
}

/**
 * Check if a given object implements the AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument interface.
 */
export function instanceOfAppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentFromJSON(json: any): AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument {
    return AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentFromJSONTyped(json, false);
}

export function AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentDataFromJSON(json['data']),
    };
}

export function AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentToJSON(value?: AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentDataToJSON(value.data),
    };
}

