/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppEventScreenshotRelationshipsAppEventLocalizationData } from './AppEventScreenshotRelationshipsAppEventLocalizationData';
import {
    AppEventScreenshotRelationshipsAppEventLocalizationDataFromJSON,
    AppEventScreenshotRelationshipsAppEventLocalizationDataFromJSONTyped,
    AppEventScreenshotRelationshipsAppEventLocalizationDataToJSON,
} from './AppEventScreenshotRelationshipsAppEventLocalizationData';

/**
 * 
 * @export
 * @interface AppEventScreenshotRelationshipsAppEventLocalization
 */
export interface AppEventScreenshotRelationshipsAppEventLocalization {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppEventScreenshotRelationshipsAppEventLocalization
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppEventScreenshotRelationshipsAppEventLocalizationData}
     * @memberof AppEventScreenshotRelationshipsAppEventLocalization
     */
    data?: AppEventScreenshotRelationshipsAppEventLocalizationData;
}

/**
 * Check if a given object implements the AppEventScreenshotRelationshipsAppEventLocalization interface.
 */
export function instanceOfAppEventScreenshotRelationshipsAppEventLocalization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppEventScreenshotRelationshipsAppEventLocalizationFromJSON(json: any): AppEventScreenshotRelationshipsAppEventLocalization {
    return AppEventScreenshotRelationshipsAppEventLocalizationFromJSONTyped(json, false);
}

export function AppEventScreenshotRelationshipsAppEventLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEventScreenshotRelationshipsAppEventLocalization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppEventScreenshotRelationshipsAppEventLocalizationDataFromJSON(json['data']),
    };
}

export function AppEventScreenshotRelationshipsAppEventLocalizationToJSON(value?: AppEventScreenshotRelationshipsAppEventLocalization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppEventScreenshotRelationshipsAppEventLocalizationDataToJSON(value.data),
    };
}

