/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityRelationshipsApp } from './AppAvailabilityRelationshipsApp';
import {
    AppAvailabilityRelationshipsAppFromJSON,
    AppAvailabilityRelationshipsAppFromJSONTyped,
    AppAvailabilityRelationshipsAppToJSON,
} from './AppAvailabilityRelationshipsApp';
import type { AppPricePointV2RelationshipsTerritory } from './AppPricePointV2RelationshipsTerritory';
import {
    AppPricePointV2RelationshipsTerritoryFromJSON,
    AppPricePointV2RelationshipsTerritoryFromJSONTyped,
    AppPricePointV2RelationshipsTerritoryToJSON,
} from './AppPricePointV2RelationshipsTerritory';
import type { AppPriceScheduleRelationshipsManualPrices } from './AppPriceScheduleRelationshipsManualPrices';
import {
    AppPriceScheduleRelationshipsManualPricesFromJSON,
    AppPriceScheduleRelationshipsManualPricesFromJSONTyped,
    AppPriceScheduleRelationshipsManualPricesToJSON,
} from './AppPriceScheduleRelationshipsManualPrices';

/**
 * 
 * @export
 * @interface AppPriceScheduleRelationships
 */
export interface AppPriceScheduleRelationships {
    /**
     * 
     * @type {AppAvailabilityRelationshipsApp}
     * @memberof AppPriceScheduleRelationships
     */
    app?: AppAvailabilityRelationshipsApp;
    /**
     * 
     * @type {AppPricePointV2RelationshipsTerritory}
     * @memberof AppPriceScheduleRelationships
     */
    baseTerritory?: AppPricePointV2RelationshipsTerritory;
    /**
     * 
     * @type {AppPriceScheduleRelationshipsManualPrices}
     * @memberof AppPriceScheduleRelationships
     */
    manualPrices?: AppPriceScheduleRelationshipsManualPrices;
    /**
     * 
     * @type {AppPriceScheduleRelationshipsManualPrices}
     * @memberof AppPriceScheduleRelationships
     */
    automaticPrices?: AppPriceScheduleRelationshipsManualPrices;
}

/**
 * Check if a given object implements the AppPriceScheduleRelationships interface.
 */
export function instanceOfAppPriceScheduleRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPriceScheduleRelationshipsFromJSON(json: any): AppPriceScheduleRelationships {
    return AppPriceScheduleRelationshipsFromJSONTyped(json, false);
}

export function AppPriceScheduleRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPriceScheduleRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': !exists(json, 'app') ? undefined : AppAvailabilityRelationshipsAppFromJSON(json['app']),
        'baseTerritory': !exists(json, 'baseTerritory') ? undefined : AppPricePointV2RelationshipsTerritoryFromJSON(json['baseTerritory']),
        'manualPrices': !exists(json, 'manualPrices') ? undefined : AppPriceScheduleRelationshipsManualPricesFromJSON(json['manualPrices']),
        'automaticPrices': !exists(json, 'automaticPrices') ? undefined : AppPriceScheduleRelationshipsManualPricesFromJSON(json['automaticPrices']),
    };
}

export function AppPriceScheduleRelationshipsToJSON(value?: AppPriceScheduleRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AppAvailabilityRelationshipsAppToJSON(value.app),
        'baseTerritory': AppPricePointV2RelationshipsTerritoryToJSON(value.baseTerritory),
        'manualPrices': AppPriceScheduleRelationshipsManualPricesToJSON(value.manualPrices),
        'automaticPrices': AppPriceScheduleRelationshipsManualPricesToJSON(value.automaticPrices),
    };
}

