/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityRelationshipsApp } from './AppAvailabilityRelationshipsApp';
import {
    AppAvailabilityRelationshipsAppFromJSON,
    AppAvailabilityRelationshipsAppFromJSONTyped,
    AppAvailabilityRelationshipsAppToJSON,
} from './AppAvailabilityRelationshipsApp';
import type { AppPricePointV2RelationshipsPriceTier } from './AppPricePointV2RelationshipsPriceTier';
import {
    AppPricePointV2RelationshipsPriceTierFromJSON,
    AppPricePointV2RelationshipsPriceTierFromJSONTyped,
    AppPricePointV2RelationshipsPriceTierToJSON,
} from './AppPricePointV2RelationshipsPriceTier';
import type { AppPricePointV2RelationshipsTerritory } from './AppPricePointV2RelationshipsTerritory';
import {
    AppPricePointV2RelationshipsTerritoryFromJSON,
    AppPricePointV2RelationshipsTerritoryFromJSONTyped,
    AppPricePointV2RelationshipsTerritoryToJSON,
} from './AppPricePointV2RelationshipsTerritory';

/**
 * 
 * @export
 * @interface AppPricePointV2Relationships
 */
export interface AppPricePointV2Relationships {
    /**
     * 
     * @type {AppAvailabilityRelationshipsApp}
     * @memberof AppPricePointV2Relationships
     */
    app?: AppAvailabilityRelationshipsApp;
    /**
     * 
     * @type {AppPricePointV2RelationshipsPriceTier}
     * @memberof AppPricePointV2Relationships
     */
    priceTier?: AppPricePointV2RelationshipsPriceTier;
    /**
     * 
     * @type {AppPricePointV2RelationshipsTerritory}
     * @memberof AppPricePointV2Relationships
     */
    territory?: AppPricePointV2RelationshipsTerritory;
}

/**
 * Check if a given object implements the AppPricePointV2Relationships interface.
 */
export function instanceOfAppPricePointV2Relationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPricePointV2RelationshipsFromJSON(json: any): AppPricePointV2Relationships {
    return AppPricePointV2RelationshipsFromJSONTyped(json, false);
}

export function AppPricePointV2RelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPricePointV2Relationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': !exists(json, 'app') ? undefined : AppAvailabilityRelationshipsAppFromJSON(json['app']),
        'priceTier': !exists(json, 'priceTier') ? undefined : AppPricePointV2RelationshipsPriceTierFromJSON(json['priceTier']),
        'territory': !exists(json, 'territory') ? undefined : AppPricePointV2RelationshipsTerritoryFromJSON(json['territory']),
    };
}

export function AppPricePointV2RelationshipsToJSON(value?: AppPricePointV2Relationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AppAvailabilityRelationshipsAppToJSON(value.app),
        'priceTier': AppPricePointV2RelationshipsPriceTierToJSON(value.priceTier),
        'territory': AppPricePointV2RelationshipsTerritoryToJSON(value.territory),
    };
}

