/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityRelationshipsApp } from './AppAvailabilityRelationshipsApp';
import {
    AppAvailabilityRelationshipsAppFromJSON,
    AppAvailabilityRelationshipsAppFromJSONTyped,
    AppAvailabilityRelationshipsAppToJSON,
} from './AppAvailabilityRelationshipsApp';
import type { AppPricePointV2RelationshipsPriceTier } from './AppPricePointV2RelationshipsPriceTier';
import {
    AppPricePointV2RelationshipsPriceTierFromJSON,
    AppPricePointV2RelationshipsPriceTierFromJSONTyped,
    AppPricePointV2RelationshipsPriceTierToJSON,
} from './AppPricePointV2RelationshipsPriceTier';

/**
 * 
 * @export
 * @interface AppPriceRelationships
 */
export interface AppPriceRelationships {
    /**
     * 
     * @type {AppAvailabilityRelationshipsApp}
     * @memberof AppPriceRelationships
     */
    app?: AppAvailabilityRelationshipsApp;
    /**
     * 
     * @type {AppPricePointV2RelationshipsPriceTier}
     * @memberof AppPriceRelationships
     */
    priceTier?: AppPricePointV2RelationshipsPriceTier;
}

/**
 * Check if a given object implements the AppPriceRelationships interface.
 */
export function instanceOfAppPriceRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPriceRelationshipsFromJSON(json: any): AppPriceRelationships {
    return AppPriceRelationshipsFromJSONTyped(json, false);
}

export function AppPriceRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPriceRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': !exists(json, 'app') ? undefined : AppAvailabilityRelationshipsAppFromJSON(json['app']),
        'priceTier': !exists(json, 'priceTier') ? undefined : AppPricePointV2RelationshipsPriceTierFromJSON(json['priceTier']),
    };
}

export function AppPriceRelationshipsToJSON(value?: AppPriceRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AppAvailabilityRelationshipsAppToJSON(value.app),
        'priceTier': AppPricePointV2RelationshipsPriceTierToJSON(value.priceTier),
    };
}

