/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppPreviewSetRelationshipsAppStoreVersionLocalizationData } from './AppPreviewSetRelationshipsAppStoreVersionLocalizationData';
import {
    AppPreviewSetRelationshipsAppStoreVersionLocalizationDataFromJSON,
    AppPreviewSetRelationshipsAppStoreVersionLocalizationDataFromJSONTyped,
    AppPreviewSetRelationshipsAppStoreVersionLocalizationDataToJSON,
} from './AppPreviewSetRelationshipsAppStoreVersionLocalizationData';

/**
 * 
 * @export
 * @interface AppPreviewSetRelationshipsAppStoreVersionLocalization
 */
export interface AppPreviewSetRelationshipsAppStoreVersionLocalization {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppPreviewSetRelationshipsAppStoreVersionLocalization
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppPreviewSetRelationshipsAppStoreVersionLocalizationData}
     * @memberof AppPreviewSetRelationshipsAppStoreVersionLocalization
     */
    data?: AppPreviewSetRelationshipsAppStoreVersionLocalizationData;
}

/**
 * Check if a given object implements the AppPreviewSetRelationshipsAppStoreVersionLocalization interface.
 */
export function instanceOfAppPreviewSetRelationshipsAppStoreVersionLocalization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPreviewSetRelationshipsAppStoreVersionLocalizationFromJSON(json: any): AppPreviewSetRelationshipsAppStoreVersionLocalization {
    return AppPreviewSetRelationshipsAppStoreVersionLocalizationFromJSONTyped(json, false);
}

export function AppPreviewSetRelationshipsAppStoreVersionLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPreviewSetRelationshipsAppStoreVersionLocalization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppPreviewSetRelationshipsAppStoreVersionLocalizationDataFromJSON(json['data']),
    };
}

export function AppPreviewSetRelationshipsAppStoreVersionLocalizationToJSON(value?: AppPreviewSetRelationshipsAppStoreVersionLocalization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppPreviewSetRelationshipsAppStoreVersionLocalizationDataToJSON(value.data),
    };
}

