/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInner } from './AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInner';
import {
    AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInnerFromJSON,
    AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInnerFromJSONTyped,
    AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInnerToJSON,
} from './AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInner';

/**
 * 
 * @export
 * @interface AppPreviewSetRelationshipsAppCustomProductPageLocalization
 */
export interface AppPreviewSetRelationshipsAppCustomProductPageLocalization {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppPreviewSetRelationshipsAppCustomProductPageLocalization
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInner}
     * @memberof AppPreviewSetRelationshipsAppCustomProductPageLocalization
     */
    data?: AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInner;
}

/**
 * Check if a given object implements the AppPreviewSetRelationshipsAppCustomProductPageLocalization interface.
 */
export function instanceOfAppPreviewSetRelationshipsAppCustomProductPageLocalization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPreviewSetRelationshipsAppCustomProductPageLocalizationFromJSON(json: any): AppPreviewSetRelationshipsAppCustomProductPageLocalization {
    return AppPreviewSetRelationshipsAppCustomProductPageLocalizationFromJSONTyped(json, false);
}

export function AppPreviewSetRelationshipsAppCustomProductPageLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPreviewSetRelationshipsAppCustomProductPageLocalization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInnerFromJSON(json['data']),
    };
}

export function AppPreviewSetRelationshipsAppCustomProductPageLocalizationToJSON(value?: AppPreviewSetRelationshipsAppCustomProductPageLocalization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsDataInnerToJSON(value.data),
    };
}

