/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppPriceTierRelationshipsPricePointsDataInner } from './AppPriceTierRelationshipsPricePointsDataInner';
import {
    AppPriceTierRelationshipsPricePointsDataInnerFromJSON,
    AppPriceTierRelationshipsPricePointsDataInnerFromJSONTyped,
    AppPriceTierRelationshipsPricePointsDataInnerToJSON,
} from './AppPriceTierRelationshipsPricePointsDataInner';

/**
 * 
 * @export
 * @interface AppPriceV2RelationshipsAppPricePoint
 */
export interface AppPriceV2RelationshipsAppPricePoint {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppPriceV2RelationshipsAppPricePoint
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppPriceTierRelationshipsPricePointsDataInner}
     * @memberof AppPriceV2RelationshipsAppPricePoint
     */
    data?: AppPriceTierRelationshipsPricePointsDataInner;
}

/**
 * Check if a given object implements the AppPriceV2RelationshipsAppPricePoint interface.
 */
export function instanceOfAppPriceV2RelationshipsAppPricePoint(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPriceV2RelationshipsAppPricePointFromJSON(json: any): AppPriceV2RelationshipsAppPricePoint {
    return AppPriceV2RelationshipsAppPricePointFromJSONTyped(json, false);
}

export function AppPriceV2RelationshipsAppPricePointFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPriceV2RelationshipsAppPricePoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppPriceTierRelationshipsPricePointsDataInnerFromJSON(json['data']),
    };
}

export function AppPriceV2RelationshipsAppPricePointToJSON(value?: AppPriceV2RelationshipsAppPricePoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppPriceTierRelationshipsPricePointsDataInnerToJSON(value.data),
    };
}

