/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationData } from './AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationData';
import {
    AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationDataFromJSON,
    AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationDataFromJSONTyped,
    AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationDataToJSON,
} from './AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationData';

/**
 * 
 * @export
 * @interface AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization
 */
export interface AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationData}
     * @memberof AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization
     */
    data?: AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationData;
}

/**
 * Check if a given object implements the AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization interface.
 */
export function instanceOfAppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationFromJSON(json: any): AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization {
    return AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationFromJSONTyped(json, false);
}

export function AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationDataFromJSON(json['data']),
    };
}

export function AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationToJSON(value?: AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppPreviewSetRelationshipsAppStoreVersionExperimentTreatmentLocalizationDataToJSON(value.data),
    };
}

