/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityRelationshipsAvailableTerritoriesDataInner } from './AppAvailabilityRelationshipsAvailableTerritoriesDataInner';
import {
    AppAvailabilityRelationshipsAvailableTerritoriesDataInnerFromJSON,
    AppAvailabilityRelationshipsAvailableTerritoriesDataInnerFromJSONTyped,
    AppAvailabilityRelationshipsAvailableTerritoriesDataInnerToJSON,
} from './AppAvailabilityRelationshipsAvailableTerritoriesDataInner';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';

/**
 * 
 * @export
 * @interface AppPricePointV2RelationshipsTerritory
 */
export interface AppPricePointV2RelationshipsTerritory {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppPricePointV2RelationshipsTerritory
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppAvailabilityRelationshipsAvailableTerritoriesDataInner}
     * @memberof AppPricePointV2RelationshipsTerritory
     */
    data?: AppAvailabilityRelationshipsAvailableTerritoriesDataInner;
}

/**
 * Check if a given object implements the AppPricePointV2RelationshipsTerritory interface.
 */
export function instanceOfAppPricePointV2RelationshipsTerritory(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPricePointV2RelationshipsTerritoryFromJSON(json: any): AppPricePointV2RelationshipsTerritory {
    return AppPricePointV2RelationshipsTerritoryFromJSONTyped(json, false);
}

export function AppPricePointV2RelationshipsTerritoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPricePointV2RelationshipsTerritory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppAvailabilityRelationshipsAvailableTerritoriesDataInnerFromJSON(json['data']),
    };
}

export function AppPricePointV2RelationshipsTerritoryToJSON(value?: AppPricePointV2RelationshipsTerritory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppAvailabilityRelationshipsAvailableTerritoriesDataInnerToJSON(value.data),
    };
}

