/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppRelationshipsCiProductData } from './AppRelationshipsCiProductData';
import {
    AppRelationshipsCiProductDataFromJSON,
    AppRelationshipsCiProductDataFromJSONTyped,
    AppRelationshipsCiProductDataToJSON,
} from './AppRelationshipsCiProductData';

/**
 * 
 * @export
 * @interface AppRelationshipsCiProduct
 */
export interface AppRelationshipsCiProduct {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppRelationshipsCiProduct
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppRelationshipsCiProductData}
     * @memberof AppRelationshipsCiProduct
     */
    data?: AppRelationshipsCiProductData;
}

/**
 * Check if a given object implements the AppRelationshipsCiProduct interface.
 */
export function instanceOfAppRelationshipsCiProduct(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppRelationshipsCiProductFromJSON(json: any): AppRelationshipsCiProduct {
    return AppRelationshipsCiProductFromJSONTyped(json, false);
}

export function AppRelationshipsCiProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRelationshipsCiProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppRelationshipsCiProductDataFromJSON(json['data']),
    };
}

export function AppRelationshipsCiProductToJSON(value?: AppRelationshipsCiProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppRelationshipsCiProductDataToJSON(value.data),
    };
}

