/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppRelationshipsGameCenterDetailData } from './AppRelationshipsGameCenterDetailData';
import {
    AppRelationshipsGameCenterDetailDataFromJSON,
    AppRelationshipsGameCenterDetailDataFromJSONTyped,
    AppRelationshipsGameCenterDetailDataToJSON,
} from './AppRelationshipsGameCenterDetailData';

/**
 * 
 * @export
 * @interface AppRelationshipsGameCenterDetail
 */
export interface AppRelationshipsGameCenterDetail {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppRelationshipsGameCenterDetail
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppRelationshipsGameCenterDetailData}
     * @memberof AppRelationshipsGameCenterDetail
     */
    data?: AppRelationshipsGameCenterDetailData;
}

/**
 * Check if a given object implements the AppRelationshipsGameCenterDetail interface.
 */
export function instanceOfAppRelationshipsGameCenterDetail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppRelationshipsGameCenterDetailFromJSON(json: any): AppRelationshipsGameCenterDetail {
    return AppRelationshipsGameCenterDetailFromJSONTyped(json, false);
}

export function AppRelationshipsGameCenterDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRelationshipsGameCenterDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppRelationshipsGameCenterDetailDataFromJSON(json['data']),
    };
}

export function AppRelationshipsGameCenterDetailToJSON(value?: AppRelationshipsGameCenterDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppRelationshipsGameCenterDetailDataToJSON(value.data),
    };
}

