/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppStoreVersionRelationshipsRoutingAppCoverageData } from './AppStoreVersionRelationshipsRoutingAppCoverageData';
import {
    AppStoreVersionRelationshipsRoutingAppCoverageDataFromJSON,
    AppStoreVersionRelationshipsRoutingAppCoverageDataFromJSONTyped,
    AppStoreVersionRelationshipsRoutingAppCoverageDataToJSON,
} from './AppStoreVersionRelationshipsRoutingAppCoverageData';

/**
 * 
 * @export
 * @interface AppStoreVersionRelationshipsRoutingAppCoverage
 */
export interface AppStoreVersionRelationshipsRoutingAppCoverage {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppStoreVersionRelationshipsRoutingAppCoverage
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppStoreVersionRelationshipsRoutingAppCoverageData}
     * @memberof AppStoreVersionRelationshipsRoutingAppCoverage
     */
    data?: AppStoreVersionRelationshipsRoutingAppCoverageData;
}

/**
 * Check if a given object implements the AppStoreVersionRelationshipsRoutingAppCoverage interface.
 */
export function instanceOfAppStoreVersionRelationshipsRoutingAppCoverage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppStoreVersionRelationshipsRoutingAppCoverageFromJSON(json: any): AppStoreVersionRelationshipsRoutingAppCoverage {
    return AppStoreVersionRelationshipsRoutingAppCoverageFromJSONTyped(json, false);
}

export function AppStoreVersionRelationshipsRoutingAppCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionRelationshipsRoutingAppCoverage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppStoreVersionRelationshipsRoutingAppCoverageDataFromJSON(json['data']),
    };
}

export function AppStoreVersionRelationshipsRoutingAppCoverageToJSON(value?: AppStoreVersionRelationshipsRoutingAppCoverage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppStoreVersionRelationshipsRoutingAppCoverageDataToJSON(value.data),
    };
}

