/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInner } from './AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInner';
import {
    AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInnerFromJSON,
    AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInnerFromJSONTyped,
    AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInnerToJSON,
} from './AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInner';

/**
 * 
 * @export
 * @interface AppScreenshotRelationshipsAppScreenshotSet
 */
export interface AppScreenshotRelationshipsAppScreenshotSet {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppScreenshotRelationshipsAppScreenshotSet
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInner}
     * @memberof AppScreenshotRelationshipsAppScreenshotSet
     */
    data?: AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInner;
}

/**
 * Check if a given object implements the AppScreenshotRelationshipsAppScreenshotSet interface.
 */
export function instanceOfAppScreenshotRelationshipsAppScreenshotSet(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppScreenshotRelationshipsAppScreenshotSetFromJSON(json: any): AppScreenshotRelationshipsAppScreenshotSet {
    return AppScreenshotRelationshipsAppScreenshotSetFromJSONTyped(json, false);
}

export function AppScreenshotRelationshipsAppScreenshotSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppScreenshotRelationshipsAppScreenshotSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInnerFromJSON(json['data']),
    };
}

export function AppScreenshotRelationshipsAppScreenshotSetToJSON(value?: AppScreenshotRelationshipsAppScreenshotSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppCustomProductPageLocalizationRelationshipsAppScreenshotSetsDataInnerToJSON(value.data),
    };
}

