/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { AppStoreVersionRelationshipsAppStoreVersionSubmissionData } from './AppStoreVersionRelationshipsAppStoreVersionSubmissionData';
import {
    AppStoreVersionRelationshipsAppStoreVersionSubmissionDataFromJSON,
    AppStoreVersionRelationshipsAppStoreVersionSubmissionDataFromJSONTyped,
    AppStoreVersionRelationshipsAppStoreVersionSubmissionDataToJSON,
} from './AppStoreVersionRelationshipsAppStoreVersionSubmissionData';

/**
 * 
 * @export
 * @interface AppStoreVersionRelationshipsAppStoreVersionSubmission
 */
export interface AppStoreVersionRelationshipsAppStoreVersionSubmission {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof AppStoreVersionRelationshipsAppStoreVersionSubmission
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {AppStoreVersionRelationshipsAppStoreVersionSubmissionData}
     * @memberof AppStoreVersionRelationshipsAppStoreVersionSubmission
     */
    data?: AppStoreVersionRelationshipsAppStoreVersionSubmissionData;
}

/**
 * Check if a given object implements the AppStoreVersionRelationshipsAppStoreVersionSubmission interface.
 */
export function instanceOfAppStoreVersionRelationshipsAppStoreVersionSubmission(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppStoreVersionRelationshipsAppStoreVersionSubmissionFromJSON(json: any): AppStoreVersionRelationshipsAppStoreVersionSubmission {
    return AppStoreVersionRelationshipsAppStoreVersionSubmissionFromJSONTyped(json, false);
}

export function AppStoreVersionRelationshipsAppStoreVersionSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionRelationshipsAppStoreVersionSubmission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppStoreVersionRelationshipsAppStoreVersionSubmissionDataFromJSON(json['data']),
    };
}

export function AppStoreVersionRelationshipsAppStoreVersionSubmissionToJSON(value?: AppStoreVersionRelationshipsAppStoreVersionSubmission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': AppStoreVersionRelationshipsAppStoreVersionSubmissionDataToJSON(value.data),
    };
}

