/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppStoreVersion } from './AppStoreVersion';
import {
    AppStoreVersionFromJSON,
    AppStoreVersionFromJSONTyped,
    AppStoreVersionToJSON,
} from './AppStoreVersion';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
} from './PagedDocumentLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface AppStoreVersionLocalizationsWithoutIncludesResponse
 */
export interface AppStoreVersionLocalizationsWithoutIncludesResponse {
    /**
     * 
     * @type {Array<AppStoreVersion>}
     * @memberof AppStoreVersionLocalizationsWithoutIncludesResponse
     */
    data: Array<AppStoreVersion>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof AppStoreVersionLocalizationsWithoutIncludesResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof AppStoreVersionLocalizationsWithoutIncludesResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the AppStoreVersionLocalizationsWithoutIncludesResponse interface.
 */
export function instanceOfAppStoreVersionLocalizationsWithoutIncludesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function AppStoreVersionLocalizationsWithoutIncludesResponseFromJSON(json: any): AppStoreVersionLocalizationsWithoutIncludesResponse {
    return AppStoreVersionLocalizationsWithoutIncludesResponseFromJSONTyped(json, false);
}

export function AppStoreVersionLocalizationsWithoutIncludesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionLocalizationsWithoutIncludesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AppStoreVersionFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function AppStoreVersionLocalizationsWithoutIncludesResponseToJSON(value?: AppStoreVersionLocalizationsWithoutIncludesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AppStoreVersionToJSON)),
        'links': PagedDocumentLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
    };
}

