/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2CreateRequestDataRelationshipsAppData } from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface BetaTesterRelationshipsApps
 */
export interface BetaTesterRelationshipsApps {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof BetaTesterRelationshipsApps
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof BetaTesterRelationshipsApps
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>}
     * @memberof BetaTesterRelationshipsApps
     */
    data?: Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>;
}

/**
 * Check if a given object implements the BetaTesterRelationshipsApps interface.
 */
export function instanceOfBetaTesterRelationshipsApps(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BetaTesterRelationshipsAppsFromJSON(json: any): BetaTesterRelationshipsApps {
    return BetaTesterRelationshipsAppsFromJSONTyped(json, false);
}

export function BetaTesterRelationshipsAppsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaTesterRelationshipsApps {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON)),
    };
}

export function BetaTesterRelationshipsAppsToJSON(value?: BetaTesterRelationshipsApps | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON)),
    };
}

