/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Build } from './Build';
import {
    BuildFromJSON,
    BuildFromJSONTyped,
    BuildToJSON,
} from './Build';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface BuildBetaDetailWithoutIncludesResponse
 */
export interface BuildBetaDetailWithoutIncludesResponse {
    /**
     * 
     * @type {Build}
     * @memberof BuildBetaDetailWithoutIncludesResponse
     */
    data: Build;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof BuildBetaDetailWithoutIncludesResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the BuildBetaDetailWithoutIncludesResponse interface.
 */
export function instanceOfBuildBetaDetailWithoutIncludesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function BuildBetaDetailWithoutIncludesResponseFromJSON(json: any): BuildBetaDetailWithoutIncludesResponse {
    return BuildBetaDetailWithoutIncludesResponseFromJSONTyped(json, false);
}

export function BuildBetaDetailWithoutIncludesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildBetaDetailWithoutIncludesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': BuildFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function BuildBetaDetailWithoutIncludesResponseToJSON(value?: BuildBetaDetailWithoutIncludesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': BuildToJSON(value.data),
        'links': DocumentLinksToJSON(value.links),
    };
}

