/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { BundleIdRelationshipsBundleIdCapabilitiesDataInner } from './BundleIdRelationshipsBundleIdCapabilitiesDataInner';
import {
    BundleIdRelationshipsBundleIdCapabilitiesDataInnerFromJSON,
    BundleIdRelationshipsBundleIdCapabilitiesDataInnerFromJSONTyped,
    BundleIdRelationshipsBundleIdCapabilitiesDataInnerToJSON,
} from './BundleIdRelationshipsBundleIdCapabilitiesDataInner';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface BundleIdRelationshipsBundleIdCapabilities
 */
export interface BundleIdRelationshipsBundleIdCapabilities {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof BundleIdRelationshipsBundleIdCapabilities
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof BundleIdRelationshipsBundleIdCapabilities
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<BundleIdRelationshipsBundleIdCapabilitiesDataInner>}
     * @memberof BundleIdRelationshipsBundleIdCapabilities
     */
    data?: Array<BundleIdRelationshipsBundleIdCapabilitiesDataInner>;
}

/**
 * Check if a given object implements the BundleIdRelationshipsBundleIdCapabilities interface.
 */
export function instanceOfBundleIdRelationshipsBundleIdCapabilities(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BundleIdRelationshipsBundleIdCapabilitiesFromJSON(json: any): BundleIdRelationshipsBundleIdCapabilities {
    return BundleIdRelationshipsBundleIdCapabilitiesFromJSONTyped(json, false);
}

export function BundleIdRelationshipsBundleIdCapabilitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleIdRelationshipsBundleIdCapabilities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(BundleIdRelationshipsBundleIdCapabilitiesDataInnerFromJSON)),
    };
}

export function BundleIdRelationshipsBundleIdCapabilitiesToJSON(value?: BundleIdRelationshipsBundleIdCapabilities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(BundleIdRelationshipsBundleIdCapabilitiesDataInnerToJSON)),
    };
}

