/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
} from './Profile';

/**
 * 
 * @export
 * @interface BundleIdWithoutIncludesResponse
 */
export interface BundleIdWithoutIncludesResponse {
    /**
     * 
     * @type {Profile}
     * @memberof BundleIdWithoutIncludesResponse
     */
    data: Profile;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof BundleIdWithoutIncludesResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the BundleIdWithoutIncludesResponse interface.
 */
export function instanceOfBundleIdWithoutIncludesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function BundleIdWithoutIncludesResponseFromJSON(json: any): BundleIdWithoutIncludesResponse {
    return BundleIdWithoutIncludesResponseFromJSONTyped(json, false);
}

export function BundleIdWithoutIncludesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleIdWithoutIncludesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ProfileFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function BundleIdWithoutIncludesResponseToJSON(value?: BundleIdWithoutIncludesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ProfileToJSON(value.data),
        'links': DocumentLinksToJSON(value.links),
    };
}

