/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { CiBuildRunRelationshipsWorkflowData } from './CiBuildRunRelationshipsWorkflowData';
import {
    CiBuildRunRelationshipsWorkflowDataFromJSON,
    CiBuildRunRelationshipsWorkflowDataFromJSONTyped,
    CiBuildRunRelationshipsWorkflowDataToJSON,
} from './CiBuildRunRelationshipsWorkflowData';

/**
 * 
 * @export
 * @interface CiBuildRunRelationshipsWorkflow
 */
export interface CiBuildRunRelationshipsWorkflow {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof CiBuildRunRelationshipsWorkflow
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {CiBuildRunRelationshipsWorkflowData}
     * @memberof CiBuildRunRelationshipsWorkflow
     */
    data?: CiBuildRunRelationshipsWorkflowData;
}

/**
 * Check if a given object implements the CiBuildRunRelationshipsWorkflow interface.
 */
export function instanceOfCiBuildRunRelationshipsWorkflow(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CiBuildRunRelationshipsWorkflowFromJSON(json: any): CiBuildRunRelationshipsWorkflow {
    return CiBuildRunRelationshipsWorkflowFromJSONTyped(json, false);
}

export function CiBuildRunRelationshipsWorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiBuildRunRelationshipsWorkflow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : CiBuildRunRelationshipsWorkflowDataFromJSON(json['data']),
    };
}

export function CiBuildRunRelationshipsWorkflowToJSON(value?: CiBuildRunRelationshipsWorkflow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': CiBuildRunRelationshipsWorkflowDataToJSON(value.data),
    };
}

