/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { CiBuildRunRelationshipsSourceBranchOrTagData } from './CiBuildRunRelationshipsSourceBranchOrTagData';
import {
    CiBuildRunRelationshipsSourceBranchOrTagDataFromJSON,
    CiBuildRunRelationshipsSourceBranchOrTagDataFromJSONTyped,
    CiBuildRunRelationshipsSourceBranchOrTagDataToJSON,
} from './CiBuildRunRelationshipsSourceBranchOrTagData';

/**
 * 
 * @export
 * @interface CiBuildRunRelationshipsSourceBranchOrTag
 */
export interface CiBuildRunRelationshipsSourceBranchOrTag {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof CiBuildRunRelationshipsSourceBranchOrTag
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {CiBuildRunRelationshipsSourceBranchOrTagData}
     * @memberof CiBuildRunRelationshipsSourceBranchOrTag
     */
    data?: CiBuildRunRelationshipsSourceBranchOrTagData;
}

/**
 * Check if a given object implements the CiBuildRunRelationshipsSourceBranchOrTag interface.
 */
export function instanceOfCiBuildRunRelationshipsSourceBranchOrTag(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CiBuildRunRelationshipsSourceBranchOrTagFromJSON(json: any): CiBuildRunRelationshipsSourceBranchOrTag {
    return CiBuildRunRelationshipsSourceBranchOrTagFromJSONTyped(json, false);
}

export function CiBuildRunRelationshipsSourceBranchOrTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiBuildRunRelationshipsSourceBranchOrTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : CiBuildRunRelationshipsSourceBranchOrTagDataFromJSON(json['data']),
    };
}

export function CiBuildRunRelationshipsSourceBranchOrTagToJSON(value?: CiBuildRunRelationshipsSourceBranchOrTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': CiBuildRunRelationshipsSourceBranchOrTagDataToJSON(value.data),
    };
}

