/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { CiMacOsVersionRelationshipsXcodeVersionsDataInner } from './CiMacOsVersionRelationshipsXcodeVersionsDataInner';
import {
    CiMacOsVersionRelationshipsXcodeVersionsDataInnerFromJSON,
    CiMacOsVersionRelationshipsXcodeVersionsDataInnerFromJSONTyped,
    CiMacOsVersionRelationshipsXcodeVersionsDataInnerToJSON,
} from './CiMacOsVersionRelationshipsXcodeVersionsDataInner';

/**
 * 
 * @export
 * @interface CiWorkflowRelationshipsXcodeVersion
 */
export interface CiWorkflowRelationshipsXcodeVersion {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof CiWorkflowRelationshipsXcodeVersion
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {CiMacOsVersionRelationshipsXcodeVersionsDataInner}
     * @memberof CiWorkflowRelationshipsXcodeVersion
     */
    data?: CiMacOsVersionRelationshipsXcodeVersionsDataInner;
}

/**
 * Check if a given object implements the CiWorkflowRelationshipsXcodeVersion interface.
 */
export function instanceOfCiWorkflowRelationshipsXcodeVersion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CiWorkflowRelationshipsXcodeVersionFromJSON(json: any): CiWorkflowRelationshipsXcodeVersion {
    return CiWorkflowRelationshipsXcodeVersionFromJSONTyped(json, false);
}

export function CiWorkflowRelationshipsXcodeVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiWorkflowRelationshipsXcodeVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : CiMacOsVersionRelationshipsXcodeVersionsDataInnerFromJSON(json['data']),
    };
}

export function CiWorkflowRelationshipsXcodeVersionToJSON(value?: CiWorkflowRelationshipsXcodeVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': CiMacOsVersionRelationshipsXcodeVersionsDataInnerToJSON(value.data),
    };
}

