/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { CustomerReviewRelationshipsResponseData } from './CustomerReviewRelationshipsResponseData';
import {
    CustomerReviewRelationshipsResponseDataFromJSON,
    CustomerReviewRelationshipsResponseDataFromJSONTyped,
    CustomerReviewRelationshipsResponseDataToJSON,
} from './CustomerReviewRelationshipsResponseData';

/**
 * 
 * @export
 * @interface CustomerReviewRelationshipsResponse
 */
export interface CustomerReviewRelationshipsResponse {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof CustomerReviewRelationshipsResponse
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {CustomerReviewRelationshipsResponseData}
     * @memberof CustomerReviewRelationshipsResponse
     */
    data?: CustomerReviewRelationshipsResponseData;
}

/**
 * Check if a given object implements the CustomerReviewRelationshipsResponse interface.
 */
export function instanceOfCustomerReviewRelationshipsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomerReviewRelationshipsResponseFromJSON(json: any): CustomerReviewRelationshipsResponse {
    return CustomerReviewRelationshipsResponseFromJSONTyped(json, false);
}

export function CustomerReviewRelationshipsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerReviewRelationshipsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : CustomerReviewRelationshipsResponseDataFromJSON(json['data']),
    };
}

export function CustomerReviewRelationshipsResponseToJSON(value?: CustomerReviewRelationshipsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': CustomerReviewRelationshipsResponseDataToJSON(value.data),
    };
}

