/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData } from './GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData';
import {
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataFromJSON,
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataFromJSONTyped,
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataToJSON,
} from './GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData';

/**
 * 
 * @export
 * @interface GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization
 */
export interface GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData}
     * @memberof GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization
     */
    data?: GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData;
}

/**
 * Check if a given object implements the GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization interface.
 */
export function instanceOfGameCenterAchievementImageRelationshipsGameCenterAchievementLocalization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationFromJSON(json: any): GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization {
    return GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationFromJSONTyped(json, false);
}

export function GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataFromJSON(json['data']),
    };
}

export function GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationToJSON(value?: GameCenterAchievementImageRelationshipsGameCenterAchievementLocalization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataToJSON(value.data),
    };
}

