/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageData } from './GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageData';
import {
    GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageDataFromJSON,
    GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageDataFromJSONTyped,
    GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageDataToJSON,
} from './GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageData';

/**
 * 
 * @export
 * @interface GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage
 */
export interface GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageData}
     * @memberof GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage
     */
    data?: GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageData;
}

/**
 * Check if a given object implements the GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage interface.
 */
export function instanceOfGameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageFromJSON(json: any): GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage {
    return GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageFromJSONTyped(json, false);
}

export function GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageDataFromJSON(json['data']),
    };
}

export function GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageToJSON(value?: GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': GameCenterAchievementLocalizationRelationshipsGameCenterAchievementImageDataToJSON(value.data),
    };
}

