/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner } from './GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner';
import {
    GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSONTyped,
    GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSON,
} from './GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet
 */
export interface GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner}
     * @memberof GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet
     */
    data?: GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInner;
}

/**
 * Check if a given object implements the GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet interface.
 */
export function instanceOfGameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetFromJSON(json: any): GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet {
    return GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetFromJSONTyped(json, false);
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerFromJSON(json['data']),
    };
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetToJSON(value?: GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': GameCenterDetailRelationshipsGameCenterLeaderboardSetsDataInnerToJSON(value.data),
    };
}

