/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityCreateRequestDataAttributes } from './AppAvailabilityCreateRequestDataAttributes';
import {
    AppAvailabilityCreateRequestDataAttributesFromJSON,
    AppAvailabilityCreateRequestDataAttributesFromJSONTyped,
    AppAvailabilityCreateRequestDataAttributesToJSON,
} from './AppAvailabilityCreateRequestDataAttributes';
import type { InAppPurchaseAvailabilityCreateRequestDataRelationships } from './InAppPurchaseAvailabilityCreateRequestDataRelationships';
import {
    InAppPurchaseAvailabilityCreateRequestDataRelationshipsFromJSON,
    InAppPurchaseAvailabilityCreateRequestDataRelationshipsFromJSONTyped,
    InAppPurchaseAvailabilityCreateRequestDataRelationshipsToJSON,
} from './InAppPurchaseAvailabilityCreateRequestDataRelationships';

/**
 * 
 * @export
 * @interface InAppPurchaseAvailabilityCreateRequestData
 */
export interface InAppPurchaseAvailabilityCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof InAppPurchaseAvailabilityCreateRequestData
     */
    type: InAppPurchaseAvailabilityCreateRequestDataTypeEnum;
    /**
     * 
     * @type {AppAvailabilityCreateRequestDataAttributes}
     * @memberof InAppPurchaseAvailabilityCreateRequestData
     */
    attributes: AppAvailabilityCreateRequestDataAttributes;
    /**
     * 
     * @type {InAppPurchaseAvailabilityCreateRequestDataRelationships}
     * @memberof InAppPurchaseAvailabilityCreateRequestData
     */
    relationships: InAppPurchaseAvailabilityCreateRequestDataRelationships;
}


/**
 * @export
 */
export const InAppPurchaseAvailabilityCreateRequestDataTypeEnum = {
    InAppPurchaseAvailabilities: 'inAppPurchaseAvailabilities'
} as const;
export type InAppPurchaseAvailabilityCreateRequestDataTypeEnum = typeof InAppPurchaseAvailabilityCreateRequestDataTypeEnum[keyof typeof InAppPurchaseAvailabilityCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the InAppPurchaseAvailabilityCreateRequestData interface.
 */
export function instanceOfInAppPurchaseAvailabilityCreateRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function InAppPurchaseAvailabilityCreateRequestDataFromJSON(json: any): InAppPurchaseAvailabilityCreateRequestData {
    return InAppPurchaseAvailabilityCreateRequestDataFromJSONTyped(json, false);
}

export function InAppPurchaseAvailabilityCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseAvailabilityCreateRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': AppAvailabilityCreateRequestDataAttributesFromJSON(json['attributes']),
        'relationships': InAppPurchaseAvailabilityCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function InAppPurchaseAvailabilityCreateRequestDataToJSON(value?: InAppPurchaseAvailabilityCreateRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': AppAvailabilityCreateRequestDataAttributesToJSON(value.attributes),
        'relationships': InAppPurchaseAvailabilityCreateRequestDataRelationshipsToJSON(value.relationships),
    };
}

