/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { InAppPurchaseV2RelationshipsContentData } from './InAppPurchaseV2RelationshipsContentData';
import {
    InAppPurchaseV2RelationshipsContentDataFromJSON,
    InAppPurchaseV2RelationshipsContentDataFromJSONTyped,
    InAppPurchaseV2RelationshipsContentDataToJSON,
} from './InAppPurchaseV2RelationshipsContentData';

/**
 * 
 * @export
 * @interface InAppPurchaseV2RelationshipsContent
 */
export interface InAppPurchaseV2RelationshipsContent {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof InAppPurchaseV2RelationshipsContent
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {InAppPurchaseV2RelationshipsContentData}
     * @memberof InAppPurchaseV2RelationshipsContent
     */
    data?: InAppPurchaseV2RelationshipsContentData;
}

/**
 * Check if a given object implements the InAppPurchaseV2RelationshipsContent interface.
 */
export function instanceOfInAppPurchaseV2RelationshipsContent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InAppPurchaseV2RelationshipsContentFromJSON(json: any): InAppPurchaseV2RelationshipsContent {
    return InAppPurchaseV2RelationshipsContentFromJSONTyped(json, false);
}

export function InAppPurchaseV2RelationshipsContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseV2RelationshipsContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : InAppPurchaseV2RelationshipsContentDataFromJSON(json['data']),
    };
}

export function InAppPurchaseV2RelationshipsContentToJSON(value?: InAppPurchaseV2RelationshipsContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': InAppPurchaseV2RelationshipsContentDataToJSON(value.data),
    };
}

