/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { App } from './App';
import {
    AppFromJSON,
    AppFromJSONTyped,
    AppToJSON,
} from './App';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
} from './PagedDocumentLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface PreReleaseVersionsWithoutIncludesResponse
 */
export interface PreReleaseVersionsWithoutIncludesResponse {
    /**
     * 
     * @type {Array<App>}
     * @memberof PreReleaseVersionsWithoutIncludesResponse
     */
    data: Array<App>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof PreReleaseVersionsWithoutIncludesResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof PreReleaseVersionsWithoutIncludesResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the PreReleaseVersionsWithoutIncludesResponse interface.
 */
export function instanceOfPreReleaseVersionsWithoutIncludesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function PreReleaseVersionsWithoutIncludesResponseFromJSON(json: any): PreReleaseVersionsWithoutIncludesResponse {
    return PreReleaseVersionsWithoutIncludesResponseFromJSONTyped(json, false);
}

export function PreReleaseVersionsWithoutIncludesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreReleaseVersionsWithoutIncludesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AppFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function PreReleaseVersionsWithoutIncludesResponseToJSON(value?: PreReleaseVersionsWithoutIncludesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AppToJSON)),
        'links': PagedDocumentLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
    };
}

