/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2CreateRequestDataRelationshipsApp } from './AppAvailabilityV2CreateRequestDataRelationshipsApp';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsApp';
import type { InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2 } from './InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2';
import {
    InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2FromJSON,
    InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2FromJSONTyped,
    InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2ToJSON,
} from './InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2';
import type { PromotedPurchaseCreateRequestDataRelationshipsSubscription } from './PromotedPurchaseCreateRequestDataRelationshipsSubscription';
import {
    PromotedPurchaseCreateRequestDataRelationshipsSubscriptionFromJSON,
    PromotedPurchaseCreateRequestDataRelationshipsSubscriptionFromJSONTyped,
    PromotedPurchaseCreateRequestDataRelationshipsSubscriptionToJSON,
} from './PromotedPurchaseCreateRequestDataRelationshipsSubscription';

/**
 * 
 * @export
 * @interface PromotedPurchaseCreateRequestDataRelationships
 */
export interface PromotedPurchaseCreateRequestDataRelationships {
    /**
     * 
     * @type {AppAvailabilityV2CreateRequestDataRelationshipsApp}
     * @memberof PromotedPurchaseCreateRequestDataRelationships
     */
    app: AppAvailabilityV2CreateRequestDataRelationshipsApp;
    /**
     * 
     * @type {InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2}
     * @memberof PromotedPurchaseCreateRequestDataRelationships
     */
    inAppPurchaseV2?: InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2;
    /**
     * 
     * @type {PromotedPurchaseCreateRequestDataRelationshipsSubscription}
     * @memberof PromotedPurchaseCreateRequestDataRelationships
     */
    subscription?: PromotedPurchaseCreateRequestDataRelationshipsSubscription;
}

/**
 * Check if a given object implements the PromotedPurchaseCreateRequestDataRelationships interface.
 */
export function instanceOfPromotedPurchaseCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "app" in value;

    return isInstance;
}

export function PromotedPurchaseCreateRequestDataRelationshipsFromJSON(json: any): PromotedPurchaseCreateRequestDataRelationships {
    return PromotedPurchaseCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function PromotedPurchaseCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotedPurchaseCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': AppAvailabilityV2CreateRequestDataRelationshipsAppFromJSON(json['app']),
        'inAppPurchaseV2': !exists(json, 'inAppPurchaseV2') ? undefined : InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2FromJSON(json['inAppPurchaseV2']),
        'subscription': !exists(json, 'subscription') ? undefined : PromotedPurchaseCreateRequestDataRelationshipsSubscriptionFromJSON(json['subscription']),
    };
}

export function PromotedPurchaseCreateRequestDataRelationshipsToJSON(value?: PromotedPurchaseCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AppAvailabilityV2CreateRequestDataRelationshipsAppToJSON(value.app),
        'inAppPurchaseV2': InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2ToJSON(value.inAppPurchaseV2),
        'subscription': PromotedPurchaseCreateRequestDataRelationshipsSubscriptionToJSON(value.subscription),
    };
}

