/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { ScmRepositoryRelationshipsScmProviderData } from './ScmRepositoryRelationshipsScmProviderData';
import {
    ScmRepositoryRelationshipsScmProviderDataFromJSON,
    ScmRepositoryRelationshipsScmProviderDataFromJSONTyped,
    ScmRepositoryRelationshipsScmProviderDataToJSON,
} from './ScmRepositoryRelationshipsScmProviderData';

/**
 * 
 * @export
 * @interface ScmRepositoryRelationshipsScmProvider
 */
export interface ScmRepositoryRelationshipsScmProvider {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof ScmRepositoryRelationshipsScmProvider
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {ScmRepositoryRelationshipsScmProviderData}
     * @memberof ScmRepositoryRelationshipsScmProvider
     */
    data?: ScmRepositoryRelationshipsScmProviderData;
}

/**
 * Check if a given object implements the ScmRepositoryRelationshipsScmProvider interface.
 */
export function instanceOfScmRepositoryRelationshipsScmProvider(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScmRepositoryRelationshipsScmProviderFromJSON(json: any): ScmRepositoryRelationshipsScmProvider {
    return ScmRepositoryRelationshipsScmProviderFromJSONTyped(json, false);
}

export function ScmRepositoryRelationshipsScmProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScmRepositoryRelationshipsScmProvider {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : ScmRepositoryRelationshipsScmProviderDataFromJSON(json['data']),
    };
}

export function ScmRepositoryRelationshipsScmProviderToJSON(value?: ScmRepositoryRelationshipsScmProvider | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'data': ScmRepositoryRelationshipsScmProviderDataToJSON(value.data),
    };
}

