/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritory } from './InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritory';
import {
    InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritoryFromJSON,
    InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritoryFromJSONTyped,
    InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritoryToJSON,
} from './InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritory';
import type { SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint } from './SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint';
import {
    SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointFromJSON,
    SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointFromJSONTyped,
    SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointToJSON,
} from './SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint';

/**
 * 
 * @export
 * @interface SubscriptionOfferCodePriceInlineCreateRelationships
 */
export interface SubscriptionOfferCodePriceInlineCreateRelationships {
    /**
     * 
     * @type {InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritory}
     * @memberof SubscriptionOfferCodePriceInlineCreateRelationships
     */
    territory?: InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritory;
    /**
     * 
     * @type {SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint}
     * @memberof SubscriptionOfferCodePriceInlineCreateRelationships
     */
    subscriptionPricePoint?: SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint;
}

/**
 * Check if a given object implements the SubscriptionOfferCodePriceInlineCreateRelationships interface.
 */
export function instanceOfSubscriptionOfferCodePriceInlineCreateRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubscriptionOfferCodePriceInlineCreateRelationshipsFromJSON(json: any): SubscriptionOfferCodePriceInlineCreateRelationships {
    return SubscriptionOfferCodePriceInlineCreateRelationshipsFromJSONTyped(json, false);
}

export function SubscriptionOfferCodePriceInlineCreateRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionOfferCodePriceInlineCreateRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'territory': !exists(json, 'territory') ? undefined : InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritoryFromJSON(json['territory']),
        'subscriptionPricePoint': !exists(json, 'subscriptionPricePoint') ? undefined : SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointFromJSON(json['subscriptionPricePoint']),
    };
}

export function SubscriptionOfferCodePriceInlineCreateRelationshipsToJSON(value?: SubscriptionOfferCodePriceInlineCreateRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'territory': InAppPurchasePriceScheduleCreateRequestDataRelationshipsBaseTerritoryToJSON(value.territory),
        'subscriptionPricePoint': SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointToJSON(value.subscriptionPricePoint),
    };
}

