/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { SubscriptionRelationshipsIntroductoryOffersDataInner } from './SubscriptionRelationshipsIntroductoryOffersDataInner';
import {
    SubscriptionRelationshipsIntroductoryOffersDataInnerFromJSON,
    SubscriptionRelationshipsIntroductoryOffersDataInnerFromJSONTyped,
    SubscriptionRelationshipsIntroductoryOffersDataInnerToJSON,
} from './SubscriptionRelationshipsIntroductoryOffersDataInner';

/**
 * 
 * @export
 * @interface SubscriptionRelationshipsIntroductoryOffers
 */
export interface SubscriptionRelationshipsIntroductoryOffers {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof SubscriptionRelationshipsIntroductoryOffers
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof SubscriptionRelationshipsIntroductoryOffers
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<SubscriptionRelationshipsIntroductoryOffersDataInner>}
     * @memberof SubscriptionRelationshipsIntroductoryOffers
     */
    data?: Array<SubscriptionRelationshipsIntroductoryOffersDataInner>;
}

/**
 * Check if a given object implements the SubscriptionRelationshipsIntroductoryOffers interface.
 */
export function instanceOfSubscriptionRelationshipsIntroductoryOffers(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubscriptionRelationshipsIntroductoryOffersFromJSON(json: any): SubscriptionRelationshipsIntroductoryOffers {
    return SubscriptionRelationshipsIntroductoryOffersFromJSONTyped(json, false);
}

export function SubscriptionRelationshipsIntroductoryOffersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionRelationshipsIntroductoryOffers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(SubscriptionRelationshipsIntroductoryOffersDataInnerFromJSON)),
    };
}

export function SubscriptionRelationshipsIntroductoryOffersToJSON(value?: SubscriptionRelationshipsIntroductoryOffers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(SubscriptionRelationshipsIntroductoryOffersDataInnerToJSON)),
    };
}

