/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks } from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import {
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSONTyped,
    AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON,
} from './AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInner } from './SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInner';
import {
    SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInnerFromJSON,
    SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInnerFromJSONTyped,
    SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInnerToJSON,
} from './SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInner';

/**
 * 
 * @export
 * @interface SubscriptionGroupRelationshipsSubscriptionGroupLocalizations
 */
export interface SubscriptionGroupRelationshipsSubscriptionGroupLocalizations {
    /**
     * 
     * @type {AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks}
     * @memberof SubscriptionGroupRelationshipsSubscriptionGroupLocalizations
     */
    links?: AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof SubscriptionGroupRelationshipsSubscriptionGroupLocalizations
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInner>}
     * @memberof SubscriptionGroupRelationshipsSubscriptionGroupLocalizations
     */
    data?: Array<SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInner>;
}

/**
 * Check if a given object implements the SubscriptionGroupRelationshipsSubscriptionGroupLocalizations interface.
 */
export function instanceOfSubscriptionGroupRelationshipsSubscriptionGroupLocalizations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsFromJSON(json: any): SubscriptionGroupRelationshipsSubscriptionGroupLocalizations {
    return SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsFromJSONTyped(json, false);
}

export function SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionGroupRelationshipsSubscriptionGroupLocalizations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInnerFromJSON)),
    };
}

export function SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsToJSON(value?: SubscriptionGroupRelationshipsSubscriptionGroupLocalizations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AppAvailabilityV2RelationshipsTerritoryAvailabilitiesLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(SubscriptionGroupRelationshipsSubscriptionGroupLocalizationsDataInnerToJSON)),
    };
}

