/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2CreateRequestDataRelationshipsAppData } from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';

/**
 * 
 * @export
 * @interface UserVisibleAppsLinkagesRequest
 */
export interface UserVisibleAppsLinkagesRequest {
    /**
     * 
     * @type {Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>}
     * @memberof UserVisibleAppsLinkagesRequest
     */
    data: Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>;
}

/**
 * Check if a given object implements the UserVisibleAppsLinkagesRequest interface.
 */
export function instanceOfUserVisibleAppsLinkagesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UserVisibleAppsLinkagesRequestFromJSON(json: any): UserVisibleAppsLinkagesRequest {
    return UserVisibleAppsLinkagesRequestFromJSONTyped(json, false);
}

export function UserVisibleAppsLinkagesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserVisibleAppsLinkagesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON)),
    };
}

export function UserVisibleAppsLinkagesRequestToJSON(value?: UserVisibleAppsLinkagesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON)),
    };
}

