/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2CreateRequestDataRelationshipsAppData } from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
} from './PagedDocumentLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface UserVisibleAppsLinkagesResponse
 */
export interface UserVisibleAppsLinkagesResponse {
    /**
     * 
     * @type {Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>}
     * @memberof UserVisibleAppsLinkagesResponse
     */
    data: Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof UserVisibleAppsLinkagesResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof UserVisibleAppsLinkagesResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the UserVisibleAppsLinkagesResponse interface.
 */
export function instanceOfUserVisibleAppsLinkagesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function UserVisibleAppsLinkagesResponseFromJSON(json: any): UserVisibleAppsLinkagesResponse {
    return UserVisibleAppsLinkagesResponseFromJSONTyped(json, false);
}

export function UserVisibleAppsLinkagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserVisibleAppsLinkagesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function UserVisibleAppsLinkagesResponseToJSON(value?: UserVisibleAppsLinkagesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON)),
        'links': PagedDocumentLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
    };
}

