/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppAvailabilityV2CreateRequestDataRelationshipsAppData } from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';
import {
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSONTyped,
    AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON,
} from './AppAvailabilityV2CreateRequestDataRelationshipsAppData';

/**
 * 
 * @export
 * @interface UserInvitationCreateRequestDataRelationshipsVisibleApps
 */
export interface UserInvitationCreateRequestDataRelationshipsVisibleApps {
    /**
     * 
     * @type {Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>}
     * @memberof UserInvitationCreateRequestDataRelationshipsVisibleApps
     */
    data?: Array<AppAvailabilityV2CreateRequestDataRelationshipsAppData>;
}

/**
 * Check if a given object implements the UserInvitationCreateRequestDataRelationshipsVisibleApps interface.
 */
export function instanceOfUserInvitationCreateRequestDataRelationshipsVisibleApps(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserInvitationCreateRequestDataRelationshipsVisibleAppsFromJSON(json: any): UserInvitationCreateRequestDataRelationshipsVisibleApps {
    return UserInvitationCreateRequestDataRelationshipsVisibleAppsFromJSONTyped(json, false);
}

export function UserInvitationCreateRequestDataRelationshipsVisibleAppsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInvitationCreateRequestDataRelationshipsVisibleApps {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataFromJSON)),
    };
}

export function UserInvitationCreateRequestDataRelationshipsVisibleAppsToJSON(value?: UserInvitationCreateRequestDataRelationshipsVisibleApps | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AppAvailabilityV2CreateRequestDataRelationshipsAppDataToJSON)),
    };
}

